```rust
use std::collections::HashMap;

// SPDX-FileCopyrightText: Copyright (C) 2023-2026 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)<lichtblick@bmwgroup.com>
// SPDX-License-Identifier: MPL-2.0

// This Source Code Form is subject to the terms of the Mozilla Public
// License, v2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/

use three::{Object3D, Scene, EventMap};
use super::*;

pub type PartialMessage<T> = T;

pub type PartialMessageEvent<T> = MessageEvent<PartialMessage<T>>;

/**
 * SceneExtension is a base class for extending the 3D scene. It extends THREE.Object3D and is a
 * child of the THREE.Scene with an identity position and orientation (origin is the render frame
 * origin). The `startFrame()` method will automatically call `update_pose()` for each Renderable in
 * the `renderables` map, placing it at the correct pose given the current renderer TransformTree.
 *
 * A minimum implementation can simply add THREE.Object3D instances using `self.add()`. If these
 * instances are Renderables and also added to this.renderables, their pose will be kept
 * up-to-date in `start_frame()`.
 *
 * - Override `dispose()` to dispose of any unmanaged resources such as GPU buffers. Don't forget
 *   to call `super.dispose()`.
 * - Override `start_frame()` to execute code at the start of each frame. Call `super.start_frame()`
 *   to run `update_pose()` on each entry in `self.renderables`.
 * - Override `settings_nodes()` to add entries to the settings sidebar.
 * - Message subscriptions are created with `get_subscriptions()`.
 * - Custom layer actions are added with `renderer.add_custom_layer_action()`.
 */
pub struct SceneExtension<
  TRenderable: Renderable = Renderable,
  E: EventMap = (),
> {
    pub extension_id: String;
    pub renderer: &mut Renderer;
    pub hud: &mut Renderer;

    pub renderables: HashMap<String, TRenderable>;
}

impl<T: Renderable> SceneExtension<TRenderable, E> {
    /** A unique identifier for this SceneExtension, such as `foxglove.Markers`. */
    pub fn new(extension_id: String, renderer: &mut Renderer) -> Self {
        let mut scene_extension = SceneExtension {
            extension_id,
            renderer,
            hud: renderer.hud,
            renderables: HashMap::new(),
        };

        // updateSettingsTree() will call settings_nodes() which may be overridden in a child class.
        // The child class may not assign its members until after this constructor returns. This breaks
        // type assumptions, so we need to defer the call to updateSettingsTree()
        queue_microtask(move || {
            scene_extension.update_settings_tree();
        });

        scene_extension
    }

    /**
     * Called when the scene is being destroyed. Free any unmanaged resources such as GPU buffers
     * here. The base class implementation calls dispose() on all `renderables`.
     */
    pub fn dispose(&mut self) {
        for (key, renderable) in &self.renderables {
            renderable.dispose();
            self.renderer.remove_child(key);
        }
        self.renderables.clear();
    }

    /**
     * Will add subscriptions from this scene extension to the renderer
     * This will be called by the renderer when building topic and schema subscriptions on
     * initialization and when imageOnlyMode becomes enabled
     */
    pub fn get_subscriptions(&self) -> Vec<AnyRendererSubscription> {
        vec![]
    }

    /**
     * Called when seeking or a new data source is loaded. The base class implementation removes all
     * `renderables` and calls `updateSettingsTree()`.
     */
    pub fn remove_all_renderables(&mut self) {
        for (key, renderable) in &self.renderables {
            renderable.dispose();
            self.renderer.remove_child(key);
        }
        self.renderables.clear();
        self.update_settings_tree();
    }

    /** Allows SceneExtensions to add options to the context menu. */
    pub fn get_context_menu_items(&self) -> Vec<PanelContextMenuItem> {
        vec![]
    }

    /**
     * Returns a list of settings nodes generated by this extension and the paths they appear at in
     * the settings sidebar. This method is only called when the scene fundamentally changes such as
     * new topics appearing or seeking. To manually trigger this method being called, use
     * `update_settings_tree()`. The base class implementation returns an empty list.
     */
    pub fn settings_nodes(&self) -> Vec<SettingsTreeEntry> {
        vec![]
    }

    /**
     * Handler for settings tree updates such as visibility toggling or field edits. This is a stub
     * meant to be overridden in derived classes and used as the handler for settings tree nodes.
     */
    pub fn handle_settings_action(&mut self, action: SettingsTreeAction) {
        unimplemented!("Handler not implemented");
    }

    /**
     * Manually triggers an update of the settings tree for the nodes generated by this extension. The
     * `settings_nodes()` method will be called to retrieve the latest nodes.
     */
    pub fn update_settings_tree(&mut self) {
        self.renderer.settings.set_nodes_for_extension(self.extension_id, self.settings_nodes());
    }

    /**
     * Persists a value to the panel configuration at the given path. The base class implementation
     * calls `renderer.update_config()` and `update_settings_tree()`.
     */
    pub fn save_setting(&mut self, path: Path, value: &dyn Into<AnyValue>) {
        // Update the configuration
        self.renderer.update_config(|draft| {
            if value.is_empty() {
                draft.remove(path.clone());
            } else {
                draft.insert(path.clone(), value.into().clone());
            }
        });

        // Update the settings sidebar
        self.update_settings_tree();
    }

    /**
     * Can be overridden to react to color scheme changes. The base class implementation does nothing.
     */
    pub fn set_color_scheme(
        &mut self,
        color_scheme: ColorScheme,
        background_color: Option<ThreeColor>,
    ) {
        unimplemented!("Handler not implemented");
    }

    /** Returns a drop effect if the Scene Extension can handle a message path drop, undefined if it cannot */
    pub fn get_drop_effect_for_path(&self, path: DraggedMessagePath) -> Option<&str> {
        unimplemented!("Handler not implemented");
    }

    /** Called when a Message Path is dropped on the panel. Allows the scene extension to update the config in response.
     * All updates across all SceneExtensions will occur in one `update_config` call.
     */
    pub fn handle_message_path_drop(&mut self, path: &str) {
        unimplemented!("Handler not implemented");
    }
}
```