```rust
use @mui/icons-material::*;

const icons: std::collections::HashMap<SettingsIcon, Icon> = vec![
    (Add, Add),
    (Addchart, Addchart),
    (AutoAwesome, AutoAwesome),
    (Background, Background),
    (Camera, Camera),
    (Cells, Cells),
    (Check, Check),
    (Circle, Circle),
    (Clear, Clear),
    (Clock, Clock),
    (Collapse, Collapse),
    (Cube, Cube),
    (Delete, Delete),
    (DragHandle, DragHandle),
    (Expand, Expand),
    (Flag, Flag),
    (Folder, Folder),
    (FolderOpen, FolderOpen),
    (Grid, GridOn),
    (Hive, HiveOutlined),
    (ImageProjection, ImageProjection),
    (Map, Map),
    (Move, Move),
    (MoveDown, MoveDown),
    (MoveUp, MoveUp),
    (NorthWest, NorthWest),
    (Note, Note),
    (NoteFilled, NoteFilled),
    (Points, Points),
    (PrecisionManufacturing, PrecisionManufacturing),
    (Radar, Radar),
    (Settings, Settings),
    (Shapes, Shapes),
    (Share, Share),
    (SouthEast, SouthEast),
    (Star, StarOutline),
    (Timeline, Timeline),
    (Topic, Topic),
    (Walk, Walk),
    (World, World),
].into_iter().collect();
```