```rust
pub const DIAGNOSTIC_SEVERITY: usize = {
  1 | 2 | 4 | 8
};

pub const SOURCES: &str = "Typescript, DatatypeExtraction, InputTopicsChecker, OutputTopicChecker, Runtime";

pub const ERROR_CODES: &str = "
RUNTIME:
  NO_DEFAULT_EXPORT: 1,
  NON_FUNC_DEFAULT_EXPORT: 2,
  NO_TYPE_RETURN: 3,
  BAD_TYPE_RETURN: 4,
  UNKNOWN_ERROR: 5,
  NO_UNIONS: 6,
  NO_FUNCTIONS: 7,
  NO_CLASSES: 8,
  NO_TYPE_LITERALS: 9,
  NO_TUPLES: 10,
  NO_INTERSECTION_TYPES: 11,
  NO_TYPEOF: 12,
  PREFER_ARRAY_LITERALS: 13,
  STRICT_MARKERS_RETURN_TYPE: 14,
  LIMITED_UNIONS: 15,
  NO_NESTED_ANY: 16,
  NO_MAPPED_TYPES: 17,
  INVALID_PROPERTY: 18,
  INVALID_INDEXED_ACCESS: 19,

INPUT_TOPICS_CHECKER:
  NO_TOPIC_AVAIL: 1,
  NO_INPUTS_EXPORT: 2,
  EMPTY_INPUTS_EXPORT: 3,
  BAD_INPUTS_TYPE: 4,

OUTPUT_TOPIC_CHECKER:
  NO_OUTPUTS: 1,
  NOT_UNIQUE: 2,
  EXISTING_TOPIC: 3
";
```